project_id = "fnoorcyskheaonrjfuam"

[functions.extract-rfp]
verify_jwt = true

[functions.health]
verify_jwt = false

[functions.draft-section]
verify_jwt = true

[functions.check-compliance]
verify_jwt = true